# Use root/example as user/password credentials

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false

  web:
    image: japan-photo-app-web:latest
    ports:
      - 3000:3000
    depends_on:
      - api
    networks:
      - japan-photo-app-network

  api:
    image: japan-photo-app-api:latest
    ports:
      - 3333:3333
    env_file:
      - "./apps/backend/.env"
    networks:
      - japan-photo-app-network

networks:
  japan-photo-app-network:
    name: japan-photo-app-network
    driver: bridge
